# Generated by Django 3.0.5 on 2020-09-22 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 14, 25, 12, 742526, tzinfo=utc)),
        ),
    ]
